site_name: Unofficial Brinkley Documentation
site_author: Steven Percle
site_description: >-
  The Unofficial Brinkley Documentation Site. Filled with Docs, Tips
  Tricks and everything Brinkley

repo_url: https://github.com/spercle/brinkley-docs
repo_name: spercle/brinkley-docs
theme:
  name: material
  font:
    text: Beausite Classic
    code: Roboto Mono
  logo: assets/brinkley-rv-logo.svg
  favicon: assets/Brinkley-B.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: deep purple
  features:
    - navigation.footer
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Model Z:
    - Model Z: model-z/index.md
    - Model 3400:
      - Model Z-3400: model-z/3400/index.md
  - Model G:
    - model_g/index.md
    - Owners Manual: model_g/manual/index.md
    - Model 3950:
      - model_g/3950/index.md
      - Interior:
        - model_g/3950/interior/index.md
        - Refrigerator: model_g/3950/interior/refrigerator.md
    - Model 3970:
      - Model G-3970: model_g/3970/index.md
  - Model I:
    - About: model-i/index.md
  - Community:
    - Contributing:
      - contributing/index.md
#      - Reporting a bug: contributing/reporting-a-bug.md
#      - Reporting a docs issue: contributing/reporting-a-docs-issue.md
#      - Requesting a change: contributing/requesting-a-change.md
#      - Adding translations: contributing/adding-translations.md
#      - Making a pull request: contributing/making-a-pull-request.md
#      - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
  - Tags: tags.md
  - Blog:
    - blog/index.md
  - 📄 Download PDF: pdf/document.pdf

  

plugins:
  - blog
  - git-authors
  - git-revision-date-localized:
      type: date
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - meta
  - glightbox
  - tags
  - with-pdf:
      author: Steven Percle
      cover_subtitle: ""
      copyright: Copyright © 2025
      toc_level: 5

extra:
  generator: false
  social:
    - icon: simple/facebook
      link: https://www.facebook.com/officialbrinkleyrv
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@BrinkleyRV
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/BrinkleyRv

copyright: Unofficial @2025


